feat: Kwenta Release
Synthetixio/kwenta pull request #343
Opened 2021-04-19 16:18 UTC by JChiaramonte7

Changes:
- fixes and improvements for the 1inch convert
- fixes and improvements for the kwenta homepage

2021-04-19 17:16 UTC, vbstreetz submitted a review, later dismissed
Looking mostly good 👍🏽

2021-04-19 17:22 UTC, drptbl requested changes
What about blockers from https://github.com/Synthetixio/kwenta/labels/convert?

2021-04-22 13:35 UTC, drptbl approved these changes

2021-04-22 17:34 UTC, justinjmoses approved these changes

2021-04-22 17:34 UTC, merged