Fix/fallback icons list
Synthetixio/kwenta pull request #379
Opened 2021-06-01 06:51 UTC by andytcf

2021-06-03 14:13 UTC, JChiaramonte7 approved these changes
Thanks for this PR @andytcf ! LGTM

2021-06-11 02:53 UTC, vbstreetz requested changes

2021-06-11 02:53 UTC, vbstreetz commented on components/Currency/CurrencyIcon/CurrencyIcon.tsx
>  	if (type === 'token') {
I discovered this prop, `token`, was actually mostly never supplied, hence the attempts to try zapper and 1inch options were being skipped..

2021-06-11 05:47 UTC, clementbalestrat approved these changes

2021-06-11 06:06 UTC, merged